name: Deploy with Policy-as-Code

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init & Plan
      working-directory: terraform
      run: |
        terraform init
        terraform plan -out=tfplan
        terraform show -json tfplan > tfplan.json

    - name: Install OPA & Conftest
      run: |
        curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
        chmod +x opa
        sudo mv opa /usr/local/bin/
        wget https://github.com/open-policy-agent/conftest/releases/download/v0.52.0/conftest_0.52.0_Linux_x86_64.tar.gz
        tar xzf conftest_0.52.0_Linux_x86_64.tar.gz
        sudo mv conftest /usr/local/bin/

    - name: Run OPA Unit Tests
      run: opa test policies/

    - name: Validate Terraform Plan Against Rego Policies
      run: conftest test terraform/tfplan.json

    - name: Deploy
      working-directory: terraform
      run: terraform apply -auto-approve
